### ISSUE TITLE
Нижний край карты (дорога, лавочки, светофоры, прохожие и т.п.)

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#10]

**Comment by Vegostar** [comment]
Низ фона к светлым и темный тайлам:


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/09ebfca4-65e3-4f85-863c-d8bc41555d69)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/9d560c66-1553-4b17-9d25-563927e35532)

**Comment by Vegostar** [comment]
как должно выглядеть

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/071a1003-0097-4cd0-8339-d389f06558a2)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4032b261-ee37-46ba-abe2-e33093c91b4c)
