### ISSUE TITLE
Кнопка меню заданий (главный экран)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#100]
Представляет из себя звенящий смартфон

**Comment by Vegostar** [comment]
Два варианта спрайтшитов, есть небольшая анимация с миганием букв.

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/47a9a419-6e81-4c5a-81a5-7b5f35fb4522)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/72fe90df-547d-467a-ad80-0abe8160c8bd)

Основную анимацию (телефон звенит) думаю легче будет сделать в godot. Примерно так:

https://github.com/Blobson/break-a-leg/assets/128842278/a08d5b7d-5858-4579-8c15-7b60dfdac6bd

**Comment by Svedmit** [comment]
Огонь! Так и сделаем!
