### ISSUE TITLE
Общий фон телефона для трех экранов (заданий, магазин, achievement)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#102]
На этом фоне располагаются три экрана (переход свайпом):
магазин (правая часть)
задания (центральная часть)
ачивки (левая часть)

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/1337a609-3efb-4607-b2e2-9dcafcebfe19)

**Comment by KarambaOne** [comment]
В качестве примера как может выглядеть 

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/93b9b12b-6819-44fe-aea1-e14ae888bca3)
