### ISSUE TITLE
Кнопка экрана заданий (нижняя часть интерфейса телефона курьера)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#105]
посылка

**Comment by KarambaOne** [comment]
Эскизы кнопки для экрана заданий
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/99b0cfac-6142-49d4-8730-2574c9fe11d0)

**Comment by KarambaOne** [comment]
Кнопка 480\480 px

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4c9b1587-ed22-4c3e-aa06-244b253222f0)
