### ISSUE TITLE
Дизайн окна заданий (экран с заданиями)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#107]
Окно со списком заданий. Для каждого задания отображается:
1. Иконка района
2. Адрес
3. Количество доставок

**Comment by Vegostar** [comment]
Итоговый вид: (размеры иконок могут немного не совпадать)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/206fc356-ba71-44a4-944b-bdb2e6677e7a)

**Comment by Vegostar** [comment]
иконки:
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/243834f0-1935-43c4-aa25-492764cede20)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/568c0ef4-6778-4aa8-b9e0-4bd9f1931167)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/ef386736-de1f-46df-9973-02a59e6aa71a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e0d6586b-9c18-4c7a-933b-337d499677e1)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/85a65789-acd1-4111-b121-611d5ebf600b)

**Comment by Vegostar** [comment]
окна + скролл

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e5ebe49d-b62a-4ea3-915a-e42419f9de45)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7dcb5302-7c50-4b56-a805-db6e8f197c98)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fd9f6a30-5b72-45fa-ad37-59f2542289ff)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4571452a-5b80-4300-9ac7-1ba79964c366)

**Comment by Vegostar** [comment]
кнопки + в активном состоянии
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/75a0cc96-f1c6-4432-aa88-c4d061765dff)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e3bddaa6-d8f3-4653-9587-fedd012f1d39)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e1dbfbb3-c61a-420f-a1cd-aae18e1aac45)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/46ceab1a-3426-4772-a0cc-2ba14c94e33e)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3d8e8f15-b2ae-494a-9703-0ccb44569e8b)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/71355628-40ad-449b-ba34-d85d8222f6af)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/457b6871-f04a-495d-90ef-20d28abc2be9)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/0a6b3ec5-80be-4c4c-aff8-ff000f773876)

**Comment by Vegostar** [comment]
Звезды с анимацией:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4ae8c5c5-678e-4c96-89b5-8725b6e56c95)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4753d990-9407-4337-b9b1-1ee272f9aab9)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/10543f11-615a-4d3b-8639-7d49acc5a04c)

У красной и зеленой есть два варианта анимации:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/a55cb61e-b100-45f6-b689-2034e3a3c560)
