### ISSUE TITLE
Тайл - центр здания сплошной

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#11]

**Comment by KarambaOne** [comment]
без окон
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/824f272c-7086-4192-b0af-dec874e80381)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b98e54ab-e608-4225-b58e-6fceb89da21b)

с окнами
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/785d8e53-a2b3-4686-bebc-231bcbc213f2)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/05c26754-d085-42bf-9dcd-cb5a21c3456b)
