### ISSUE TITLE
Кнопка "доставить заказ" - начать играть (экран с заданиями)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#110]

**Comment by KarambaOne** [comment]
Эскизы кнопки для доставки заказа

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c10bf2b6-53f2-4661-85c8-67bc8005ceee)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2027ead2-938e-45f7-a72c-0bbf97e79c91)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/99dacb55-6fc1-41c5-b743-f222246668f8)
