### ISSUE TITLE
Разработать символ внутриигровой валюты

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#113]

**Comment by KarambaOne** [comment]
версия 16px
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/efa89519-a1fe-4336-a7d2-a69602351e76)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/59e9edd9-a0d9-4fae-8d2d-262e66fb01d7)


версия 64px
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/8ca42e2e-d3ab-4acf-8a88-47d4cbcf3e37)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ea23a87f-ba5c-4420-988b-24a53ac0989d)
