### ISSUE TITLE
Иконки абилок

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#115]
1. Крюк (вантуз с веревочкой)
2. Щит (зонтик)
в активном и неактивном виде (чб)

**Comment by KarambaOne** [comment]
Эскизы к иконкам абилок 

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/3821bd81-9b3c-472d-ad43-9158e8d90c00)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ad3def4d-7d3a-4305-a531-50282c2aafc2)

**Comment by KarambaOne** [comment]
Иконки на 480\480

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ddd2d683-15d7-4964-90d7-3361d5d2d9b6)

![Image](https://github.com/Blobson/break-a-leg/assets/130583246/6a502e3f-0edb-4968-bdc7-c670826ae21f)
