### ISSUE TITLE
Успешное прохождение (экран окончания уровня)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#120]
Вверху экрана круглая иконка с анимацией "курьер пересчитывающий заработанное баблишко" (или что-то подобное по выбору художника, показывающее успешность прохождения задания).

В центре экрана списком:
 - заработанные скуты (монетки)
 - доставленные посылки (например: 3 из 5)
 - качество прохождения (рейтинг) - максимум 5 звезд

В нижней части экрана суммарный текущий рейтинг игрока от 0 до 5, может содержать десятые доли (например 3.7)

В нижней части экрана кнопка "в главное меню".

**Comment by Vegostar** [comment]
общий вид: (+ анимация с курьером)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/00f03e0d-0348-4ddc-bf3a-463db552b85f)

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/505c963c-c43a-497b-a79e-1589363820bb)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3c2c7f79-cccc-4bfa-8ca8-1a8ec0f4ddbc)

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/2a996c55-a7e4-404b-8758-ce7473028993)


конфетти на переднем плане: (первые кадры пустые, это чтобы соответствовало времени взрывания основных хлопушек)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1f979515-0d04-419a-aee5-f9d76af29289)

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/541dc883-c703-4f7f-961a-596ec9464664)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fbf07ce4-a4ff-4e02-ad25-097a221fe93e)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/365131ba-122d-49a7-9322-4beb6e6acf36)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d891bfb5-a60b-4909-a2b8-773944e3ef09)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/384eae2e-128f-4f1c-b30e-93a29bad617a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/45433dca-5869-4771-9b53-08f46d960848)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7d62cd5c-bfa3-47c6-86df-65b36a15e845)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/ae7ec36f-6e7c-48a7-a7fc-aa24cc9bd3a9)
