### ISSUE TITLE
Неудачное прохождение (экран окончания уровня)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#121]
Вверху экрана круглая иконка с анимацией "курьер бинтующий ногу" (или что-то подобное по выбору художника, показывающее неудачность прохождения задания).

Остальное полностью повторяет экран успешного прохождения.

**Comment by Vegostar** [comment]
общий вид:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/db54f91c-3a7a-46ed-99c2-af48f7dda228)


анимация:
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/0053fd76-7972-4bae-9d48-d8d8b5a20fab)


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3b7b3963-428a-4f77-a712-65da24af62b6)

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/560ffda2-e49d-4325-bcfb-2474d1d40d89)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d798b37a-dee6-44bd-abdf-479a155d666c)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/cabc38ae-241a-4d88-95b7-3960c6b63e6a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/37c26c2d-2d10-4c34-b19e-1342ead9f0b5)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/be27aba3-e366-418d-b5e5-2f8eae4bde44)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/b5b3746b-5ce0-4cda-a91f-31fbc5fbf137)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/6c08dd9a-234e-44bb-a9f6-215de8ed6939)
