### ISSUE TITLE
Тайл - входная дверь

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#14]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d051effe-1631-41e2-91bf-ff3457834d30)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f365e5f4-21df-4e31-a594-ec696aff1097)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f3c03220-2ddb-499c-a75a-a16f64121f11)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d4934b06-ac80-4127-8339-7ef4c208a44d)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/12179a3a-a3ca-435f-9f5a-ff40edff7e19)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/acb2bb83-55ab-4c5f-972a-a7863a4cdda6)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/005904c4-62bc-4496-91ee-4eb31dbec0ec)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/10cf44ff-ece7-4270-8073-6d929e963fd7)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/5a95cca0-f09f-4d77-b1e2-ad2e4eedc028)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c3930cb6-d0f1-428d-ad52-88574589e63f)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0486f417-1e6d-4eea-8b2d-76941928eeee)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/088e99a7-9ade-412b-9c2e-be291cb4f09d)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/513de4b3-4813-46c3-9f73-65cb0a15edcf)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4181bc2c-b5b8-412e-a027-d3241cb484a8)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/5eca2f50-f8f3-4b57-9aeb-2561be4a986f)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7026813b-b97d-4fd7-86f7-b54e6338fb39)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/323d5b63-d730-48fe-936c-8c194b431fa0)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c453eae0-3021-4b69-affd-4061d9d8f29c)
