### ISSUE TITLE
Универсальная анимация восстановления курьера после столкновения

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#166]
Это универсальная анимация последствий для курьера после любого столкновения - "Потрепанный курьер на бегу поправляет внешний вид".

В частных случаях, например для столкновения с кондиционером будем заменять данную анимацию на что-то поинтереснее.

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/5c110049-0313-45c3-962a-bfdd97f8ec2a)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/3afa6f6e-ee1f-4ec1-85e0-20ea14519bba)
