### ISSUE TITLE
Анимация - кошка спит на подоконнике

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#167]

**Comment by Vegostar** [comment]
Гифка с тем как выглядят все действия сразу без повторов:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d4f29aa6-52a8-45b9-8335-a3cfa2059a0a)



Спрайтшиты:


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/cfcfa197-a693-4340-a8a1-e4695c2ba765)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3a06a5a8-e658-495a-9cdc-bd498d2624ce)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/35005c7d-53c2-445b-b2d8-78897c421ab9)
