### ISSUE TITLE
Art: Плакат или граффити

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#17]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/24358708-bd35-438e-ae79-44db610786d0)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/23c0aa9d-d8b6-42e6-92aa-b95d10f223d9)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f5ba80f9-de38-4208-9086-8068bb217919)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e77823f0-efc4-4777-8761-abe71d79f385)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/1bdd3ba1-5a96-4911-b07a-15bbe747a905)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/8a2d4b0e-21ba-43e4-b8ad-aef491808bd4)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7128d361-f248-464b-9cfe-00e9e628dabf)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/6e7ecff4-3e52-4e43-b253-483758ab93ed)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2457625f-daa1-4249-8874-68335ba59c26)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/39a3e337-2bf0-422a-8569-c263cc7309d2)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/36497f36-563c-459e-86ec-453792f9acba)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e0f0fd2d-b072-403c-a128-e2db56d4a474)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4b1a8658-74a3-44bb-a5f4-a097e9a0bd15)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/87f5ff92-7572-4895-9f5d-cdc12c2cf83e)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/15327c4c-83eb-4dc0-abef-41e1132b236b)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/76b6aa1e-c5da-4398-b7ff-aa1667fe3541)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4ebe73b4-2fa7-4e6d-966a-0be4cf10c41d)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2d93231e-1739-42ca-a9b9-fbfc79999414)
