### ISSUE TITLE
Анимация атаки кошки

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#170]
Две анимации:
 - кошка прыгает на курьера
 - кошка царапает курьера (можно использовать существующую)

**Comment by Vegostar** [comment]
Прыгает на курьера:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/88302ad3-b89f-4daf-970e-c91f5f9a7883)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/04434c5d-030c-4d45-a99e-a76bb7538ffa)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/f10c29be-210a-4585-b747-755453e49d68)


царапает:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/84026406-3d1f-466c-9ab5-14065f2a2f33)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/caa1ba03-b503-4a84-a449-0fa8d074da15)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/5c8a442c-9a67-4d0f-80eb-14edc5c74d35)
