### ISSUE TITLE
Анимация столкновения с кошкой

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#171]
Взрыв/облако пыли, шерсть и пыль разлетаются (короткая - 1сек макс)

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/63d8a54b-801e-4627-896f-968209383063)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/a6943097-c7af-4f25-bd82-f83e0e8dc1ea)

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2da71b6f-d7b1-4437-b384-7facf81eb1c3)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/64868566-2d8b-4541-82c7-b2c9815dd57e)
