### ISSUE TITLE
Анимация -  кошка летит вниз сброшенная курьером

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#172]

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/16549518-bd57-4543-b258-45759c4dac5f)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4cd72ee6-8c17-44aa-904e-772a785f9246)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/b9540e0c-d56e-4de6-be3f-3be61a3add31)
