### ISSUE TITLE
Анимация - цветок атакует пробегающего курьера

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#174]
Цветок вытягивается на соседний блок вправо или влево наносит урон (если игрок пробегает рядом)

**Comment by Vegostar** [comment]
Новый вариант: (статика, атака, поворот)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/81a4eeb5-d01d-4abb-88a1-95a563835070)

статика:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/8d33060e-82f2-4fe4-a447-e5f9229d288a)

атака:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/80a586c3-fbaf-4c06-8ee6-a4dc1a9141d0)

поворот:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/729fe0df-2cab-493a-bbc1-8d054f06adfd)
