### ISSUE TITLE
Анимация - горшок ломается, если игрок пробегает по цветку

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#175]
Требуется для всех видов цветков

**Comment by Vegostar** [comment]
как выглядит переход от статики к разрушенному состоянию:
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/a2017658-4547-4295-8750-35ef7bbed469)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/ce212b26-7f77-49ea-80c3-bc3911a8d02f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/0e1ab62d-9240-4fbc-9529-ce68a5cc897f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/71c79134-7e55-49be-8371-3c30645e9aeb)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4ae9a65b-bc44-447b-8ae7-22427025109f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fd18d837-bef3-4cfc-b320-1168a4b1b709)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/30fd18ba-2d42-4b34-bfeb-cf9d28f96ebc)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d11a6711-954d-42a4-a81b-386f45b52bf8)

Не уверена насчет размера и получится ли добавить анимацию, так что на всякий случай просто картинки 32х32:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/8805475c-96db-4006-94d2-eea61818954c)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/837806e8-9562-4dd6-ac63-69d9aa4fe54e)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/78b8c2a8-7e7d-45db-b405-e02ad033a6b1)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e4594d9b-52dc-4e6d-9349-1d78b0141199)
