### ISSUE TITLE
Анимация - "возглас" вылетающий из окна (3-5 разновидностей)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#183]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/139454dc-6354-498d-b64e-b6123a3819b1)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7865394f-b412-49e9-91a0-994917df79b9)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2df8e6e6-51ce-44d9-91e7-da97d2af605d)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b603116a-d33d-4048-be56-20e16a64e743)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/62768241-eccd-45fa-82cf-0c86e6b00821)

**Comment by KarambaOne** [comment]
Новые актуальные реакции для окон и окон клиентов

Последняя реакция для бакби, теряющая ковер 


![Image](https://github.com/Blobson/break-a-leg/assets/130583246/995934f7-8343-46a1-9608-6bc8ec7b9491)
