### ISSUE TITLE
Анимация - открытое окно, в котором стоит машуший клиент(ы)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#186]
3-5 разновидностей - пара, один взрослый, ребенок или собака

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/8f2dd467-2cdc-4d22-bd66-1d553832353a)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/54d9aba7-6cc0-49e8-819d-71b7cab956af)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/9ec7df42-d621-4675-ba6e-1250a2cce073)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/fa18cd30-d3a3-415f-a27b-0f4959379adb)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0f84b3fd-9307-477a-ae5d-054d61752b44)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/83552052-f6d7-45f8-af07-6177e7018d33)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/32b87aae-fd9f-4465-b8b7-6a0605b5ada9)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d5590ff4-9f53-4374-a9ce-2245c3ec96c7)
