### ISSUE TITLE
Анимация получения заказа

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#188]
Довольный клиент стоит с посылкой в окне и благодарит убегающего курьера. (3-5 видов)

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/6fbb171a-f0ab-4d30-97b3-e78c8d764625)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/27993571-282b-4923-970d-40b677e22036)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c1552b7b-190b-4110-abbc-0e4ac2c2867b)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c878caf7-1e05-451f-b080-9760a70ad96f)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e1aa8ba7-19e8-4720-890d-3cb1343a7aba)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/cdde858f-f928-4b45-9172-1eee3df26426)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f3ae21a5-acde-49f1-b5c8-db67d9c2d7ba)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/5e59b31f-d2a8-4635-9672-959324ed0a5e)

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f92258e1-e8c1-429b-ac65-e147abe22f1b)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/735c5be5-e58c-4523-b87b-f346df4d8a4b)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c019e5d6-615e-4765-bfd5-c01942ba9e02)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/56d831a9-561f-4673-8fa0-7faadd4b1aa5)
