### ISSUE TITLE
Art: Окно с колючим растением, наносящее урон при столкновении

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#19]

**Comment by Vegostar** [comment]
Размеры х1, х10
растения немного двигаются, поэтому все спрайтшитами

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/249d7fa1-5215-41f9-ac14-43cf0bf9db52)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7b72efc6-f470-4a11-afa5-d6b6e0f0cf1d)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d63cb11a-2572-4bad-b397-ceff75098f8b)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7560991b-a7b2-4bf6-98e6-70f8ae4c2dfd)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/287ad081-5226-4bfd-a6b1-4e84a60c1779)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/829061f1-a680-4e86-ac19-f326b24c1aba)

**Comment by Vegostar** [comment]
У одного варианта есть анимация нападения

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/91abd458-c67c-4df0-bb6b-a86010299bc4)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3b0013bf-ef34-4178-a5e0-56e43714d07d)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/73e43479-82b1-4e96-80c3-8c689086ed61)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/c597c0ef-2f48-49ef-88ba-79c31887f28e)

**Comment by Vegostar** [comment]
как должно выглядеть

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3068ea19-1462-4bea-838a-01f5f8b881db)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/27f66ca4-aee3-41ba-9bfe-25821bebacbf)

**Comment by Vegostar** [comment]
То же самое без фона
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d03be63b-cc67-4846-954b-5fd8c07967d1)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/525fd82f-4341-4244-b30e-47c70f8b130a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/f617208a-c5e9-4cde-a4fa-c6e6f0fd4f0a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/c7969188-82dd-494c-a50a-139c506bbf30)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/32744989-64d5-4a8c-98d9-e856321df723)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/ce936d8e-b7e7-4a52-af69-94d950f01eee)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1468b59a-9b77-4e6c-beea-609a69ce214a)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/bd931d2f-003a-4dee-ba8f-36e6d89bea02)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/dd10872e-df2f-43a9-bfd1-ce61f4fa1ffc)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fa1c66dc-c464-4414-a9e2-72c8e7745b4d)
