### ISSUE TITLE
Анимация джет-пака

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#201]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7106d7ae-800a-423c-860e-6e967bc51486)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/9870f708-9b59-4520-affc-d1574f1a5d1b)




![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4029bd02-d20b-4935-8fec-72bff620a661)
