### ISSUE TITLE
Разбить сердечки

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#206]
В одном сердце 4 кусочка

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/9144d61d-c69b-414b-bac9-1660f9816a81)


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1a4612f0-796a-4912-9218-209d7093dfa7)


кадры: (1-4 разрушение по одной части)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/4e353baf-55ea-4cfd-8f5e-e5558fcd6000)
