### ISSUE TITLE
Исправить индикаторы жизней и энергии

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#207]
Увеличить иконки индикаторов жизней и энергии, выровнять их по разрешению и размеру

**Comment by Vegostar** [comment]
Жизни в #206 


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/8d99332c-30cd-4840-8268-41621450e0b9)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/60b4b5a9-db1d-4ebe-9b39-9005f46bd2dd)



кадры: (добавила постепенное снижение и накопление к прошлому варианту)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d49325d9-ddb6-498a-9bf8-7b5317c4313b)
