### ISSUE TITLE
Art: Кондиционер разрушаемый при столкновении и наносящий электрический урон

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#21]

**Comment by Vegostar** [comment]
Размеры х1 и х10, анимации нормального кондея и разрушенного

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/103b4491-83d6-428c-a02c-ea8203a13edd)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/3365eeb1-d546-4e75-a561-27f3d18c012f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/be12340d-1f56-45aa-b794-539f68766566)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1d3b7949-1cb1-4292-b590-cbf8bef18c01)

**Comment by Vegostar** [comment]
гифки с тем как должно выглядеть

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1c9b8560-4168-4dcd-be71-84ded9c838b3)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/47602925-706d-4ef9-ac90-0ea8a2abb7b5)

**Comment by Vegostar** [comment]
все спрайты одним файлом
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/26841b26-1b2f-4e73-aadb-9bd614fe94a9)
