### ISSUE TITLE
Анимация - бабка трясёт ковром

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#218]
Отдельно две анимации:
 - бабка стоит в окне с ковром в руках (можно статический спрайт, но лучше анимацию)
 - бабка вытряхивает ковёр
Из текущего варианта надо убрать процесс открывания окна.

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/68e620ee-cfb6-4f06-956e-fee33977a4c4)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/f39f89c9-12b6-4a1f-814e-7757a8973147)
