### ISSUE TITLE
Анимация - облако пыли растворяющееся в воздухе

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#219]
Облако пыли клубится и потом растворяется.
Время обоих процессов будет подбирать программист прикручивающий анимацию.

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/5b1e6382-f0ad-41d1-ae5c-8bc1c8f8ca66)


гифка для референса 
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/4c96ad16-71cc-4ce7-96f1-143a7bcc3989)
