### ISSUE TITLE
Анимация курьера попавшего в облако пыли - курьер чихает и отряхивается.

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#221]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0b90e924-fcb3-4ef7-a4b9-347267d21894)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e555fc48-4dc2-4117-8ef6-563c3537b2c9)
