### ISSUE TITLE
Анимация - курьер запутался в ковре, если пробежал через окно бабки трясущей ковром

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#222]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/642341bf-1395-4efe-8d99-04004ff3a7c2)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ab06606e-8b14-4c60-bc86-81324fc197f8)


Объединил ко всем
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e8dbf59f-bef3-4d4f-9e9f-8726bdf5e391)
