### ISSUE TITLE
Анимация - бабка теряет ковер, начинает ругаться и грозит клюкой

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#224]

**Comment by Blobson** [comment]
Извиняюсь, тут я накосячил - надо было более подробно описать задачу.
Исправляюсь...
По задумке бабка должна терять ковёр когда курьер пробегает по этому окну и запутывается в ковре.
Я думаю Дима как главный идеолог может объяснить более подробно.

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/cdacf397-e315-4f27-8c21-c73b4ff973b0)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c5dc50ec-4a58-4bb2-b427-1c5c60a39e82)
