### ISSUE TITLE
Art: Окно со спящей кошкой, нападающей при приближении

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#25]

**Comment by Vegostar** [comment]
1-6 кадры — статика
7-18 — удар

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/981ee406-e52e-409a-a6e2-65b4dc59e2ee)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/a42a2534-0041-4f08-b6f7-16f861095861)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7ae49222-7502-4c43-afbd-85f8d9f35de6)

как должно выглядеть:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/dff3181e-40a0-4e05-ba7e-74eca2b3d652)
