### ISSUE TITLE
Art: Птицы летающие по горизонтали (вороны, сороки или голуби)

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#28]

**Comment by KarambaOne** [comment]
Скорость анимации 100-125 миллисекунд для всех. Гифка для представления  
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/857a51f5-5a9d-4408-8b90-40966104c175)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/72ffa5a5-f222-4954-a7f2-5afde6544b17)
