### ISSUE TITLE
Ретро 2023-12-30

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#294]
Ретро:
 - Фиксировать майлстоуны более жестко (1 месяц / 2 месяца)
 - 2-х недельные спринты
 - Озвучивать рефакторинг коллегам
 - Задания художников требуют более тесного обсуждения среди художников
 - Задания нужно описывать более подробно

Предложенные улучшения по игре:
 - озвучка
 - кнопка Pause
 - кнопка Mute
 - генератор
   - привязать сложность игры к генератору
   - минимальное расстояние между препятствиями (кондеи, кошки и кусающиеся цветы)
   - маскимум 2 окна подряд
   - баннеры не должны наезжать на окна
 - индикаторы падающих предметов (восклицательные знаки)
 - анимация перехода на окончание уровня
 - переделать анимацию получения заказа
 - добавить индикатор энергии на сумку курьера
 - переделать анимацию бега по стенам
 - тени и освещение
   - тени от препядствий
     - тень от кондиционера
     - тень от цветов
     - тень от птиц
     - тень от кошки
   - тень от курьера
 - прорисовка фона уровня
   - положить шум на стены дома (шейдер)
   - сделать блики на окнах (шейдер)

**Comment by VasyaLel** [comment]
1) новые здания
2) возможность менять общее фоновое освещение
3) ? возможность нижним свайпом включать какой-то буст персонажа (щит, ракету)

**Comment by VasyaLel** [comment]
какой-то визуальный эффект на персонаже от потери здоровья (а то сейчас вообще непонятно, что ты теряешь здоровье если на него не смотреть)

**Comment by Svedmit** [comment]
Убрать замедление на окнах

**Comment by Bartolemy12** [comment]
Пофиксить звук при нажимании по экрану (должен срабатывать только при нажимании на иконки)

**Comment by Vegostar** [comment]
1.	При входе в игру непонятно что происходит. Нужно коротко объяснить в чем суть, что гг доставщик и это его главная цель на уровне. Можно прям на главном экране показать, там есть свободное место для этого. (сказали непонятно почему такой большой список заданий и что значит деливер) + здесь же нужно объяснить название игры, можно прямо в конце объяснений добавить «break a leg!», типа пожелание удачи.
На уровне нужно объяснить как работают препятствия, за что и сколько отбирается жизней, зону действия и как избежать. (непонятно что цель, а что препятствие) 
Объяснить как доставлять посылки. + можно более четко обозначить основную цель – например, подняться в рейтинге. 
2.	На уровне очень резко и громко включается музыка – нужно плавное включение и мб звук снизить
3.	Неудобное управление. Нужен джойстик или гироскоп.
4.	Я бы уменьшила зону действия (?) окна. Потому что когда окна близко расположены и приходится быстро перемещаться, даже если ты стараешься подобрать правильное время, все равно очень легко задеть угол окна, что отнимает жизнь. Когда прыгаешь тоже сложно подобрать время, мне кажется, стоит облегчить этот процесс. (ну и я бы сами окна более рандомно и подальше друг от друга расположила, чтобы пользователь больше влево-вправо прыгал, чем вверх)
5.	Если мы пока что не будем делать другие районы, то можно хотя бы менять цвет дома + дать возможность изменить цвет курьера. (и я бы посмотрела как тайлы смотрятся с шумом)
6.	Из мелочей: сейчас почему-то засчитываются сверху даже те посылки, которые не были доставлены. При удачном прохождении на экране окончания уровня черный экран, и с сердечками что-то страшное случилось. Друзьям музыка понравилась, но немного хрипит местами. Я бы перерисовала стрелку на уровне, которая на заказчиков указывает.


Говорят, еще хотелось бы поднять мотивацию, но это к магазину, насколько я понимаю. (По-моему вышло так, что игра похожа на сабвей серф, а там главный прикол в том, чтобы заработать на новый скин. Мб нам тоже следует потратить на это время)


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/45a954d3-ddad-4e65-bc9d-9a43b6a99c67)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/9b1ec1b2-5251-40c2-8ad7-6d814e013c94)

**Comment by Vegostar** [comment]
7. Предложили еще в начале уровня сделать паузу и дать игроку возможность самому проконтролировать начало бега
