### ISSUE TITLE
Art: Цветок в горшке летящий вниз

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#30]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/18d12b80-ac07-470a-8861-facddf197d35)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/086ee035-dd2e-4dbf-a56a-fac1ef8fa162)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/22d4e33d-1a89-48aa-b5e5-2562fb33a3f2)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7700a334-740a-4de1-af79-27fa4c951a3d)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ce9d8f60-3045-4fc9-9e6b-7d6381a0c0ae)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/c8a22f30-5783-41b0-83c7-8d7ad40db950)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e3ab67b4-e5da-41a3-ab6b-ab41064ea7d5)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b894eadb-b635-4430-b631-f4d07d86ad40)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/286d0dce-fc3b-4065-a3b7-01358c95741e)
