### ISSUE TITLE
Art: Ботинок летящий вниз

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#32]

**Comment by KarambaOne** [comment]
Скорость анимации эффекта 75 миллисекунд
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/ab2d3f6f-4cd3-4e5d-98c2-59f0ad36be16)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/37d013b6-cd94-4234-aa04-8768510b9b96)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/18b6ff56-f01c-400c-bc27-e1da30d2d70e)

**Comment by KarambaOne** [comment]
Увеличил размер на 30%
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0564ff9d-b462-483f-a8f8-e95238196e3a)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/1abea923-b00e-42b2-ae62-f594dee31baf)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f4c5f797-8e7a-4c2b-9d31-1adf0530f3ef)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/36ea8b24-d46a-4aeb-a6d1-cb1a3d6d13c5)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/95a9ba9a-347e-4b62-8d20-2653dc0aad8e)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/7e34a39a-c04f-471a-bc89-a698f0e2a856)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d2c10102-6335-4281-a1b7-eb73507ab159)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/bf1499f9-e5ba-41f7-a8d4-4df81c27b76b)
