### ISSUE TITLE
Создать несколько разновидностей тайлов обстановки комнат

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#320]
Хотим добавить прозрачности тайлам окон и подкладывать под них обстановки комнат:
 - книги на подоконнике
 - растения в горшках
 - люди сидящие за столом, пьющие чай
 - и т.д. и т.п.

Требуется 3 вида тайлов:
 - для полноразмерных окон
 - для форточек
 - для узких окон на краю здания

Размеры тайлов 32х32, чтобы было легко подкладывать под тайлы окон.

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/cd1982fa-2478-4fc3-a4bb-7b086fe3afb5)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d347f727-6f8c-4600-8730-7c42847fa216)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/d6ad403d-9543-418e-95d3-796bb6d1698b)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/61b72524-7126-4cd6-bd21-373ed3d3f453)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b45b9431-36c4-482d-8b17-362d296f0e09)
