### ISSUE TITLE
Изображение персонажа

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#35]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/a8d96f97-0cca-41a5-9dbf-fd0da36f90e5)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/3bb6a45a-2887-4927-94d5-84915713f04b)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0b92be01-8982-4200-8b42-24c2c4893a42)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/9f9192c1-7372-47b5-a423-0ce1d4940f17)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/a87de66e-bbd1-4d64-bffd-3aab58ab9800)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/9530dab2-2b6d-4e9b-8ca8-74caa9ee86a6)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/196b3f53-f98e-4b66-9d90-63f8f88d8797)
