### ISSUE TITLE
Анимация бега (вверх-прямо, вверх-влево, вверх-вправо)

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#36]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/a77cf097-1691-4375-87bb-80a2cf4a0044)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b7d625ec-31ac-4e84-be1a-05efb79afe20)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/68c8ba98-3d15-4f20-af0d-1ce66f2b8323)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/909ecf2b-8ff9-45d5-9b22-7982feb3078e)
