### ISSUE TITLE
Анимация парашютирования (по окончанию уровня, при исчерпании жизней)

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#39]

**Comment by KarambaOne** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/b2924875-ba44-4af8-8c5e-42e2c597bb25)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/3e6b8438-508b-4290-8170-6e57075b220c)
