### ISSUE TITLE
Предупреждение о падающий предметах (дизайн иконки)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#392]

**Comment by KarambaOne** [comment]
Пример
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2c193265-6eb7-48ef-a128-65f5a282951c)


Спрайт шит
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/37e1b84d-115a-4e4a-849b-7aa53c6d9991)

Расстановка кадров. Скорость примерно 10 кадров в секунду. 
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/f55146ca-1c52-4700-9391-ee739dc24eae)
