### ISSUE TITLE
Нарисовать иконку для игры

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#58]
Требуется сделать иконку для игры согласно [руководству](https://docs.godotengine.org/ru/stable/tutorials/export/exporting_for_android.html#providing-launcher-icons)

**Comment by Vegostar** [comment]
слои для адаптивной иконки (432х432):

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/6518523a-913f-4418-ab7c-4e022b706fb0)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/244e9ba1-297c-40fe-abfe-0a9512e48991)
