### ISSUE TITLE
Анимация персонажей к низу фона

### ISSUE THREAD

**Issue by Vegostar** [Blobson/break-a-leg#84]

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/6cbe6f9d-7bf3-41a6-b984-3f581a03c305)


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/dfb023da-a8d9-45ea-8783-b4ab24104ddc)





![Image](https://github.com/Blobson/break-a-leg/assets/128842278/bbcd9876-009f-4e27-843f-19914eb8b2e6)


![Image](https://github.com/Blobson/break-a-leg/assets/128842278/c2572fae-d049-40e8-be5b-55c0909f9017)

**Comment by KarambaOne** [comment]
Скорость где-то 8 кадров в секунду
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0ee63adc-9e82-40c7-af20-1fb2d67d5abd)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/2f8c7820-470c-4ea1-a89a-c959954495ce)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/e9d706fc-31eb-4b7b-b4db-3f783a7bb5ca)



![Image](https://github.com/Blobson/break-a-leg/assets/130583246/0fb5ed6b-291a-4c19-912a-633c7d6e0235)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/3c004eff-02c0-4653-815e-47fa23b0374f)
![Image](https://github.com/Blobson/break-a-leg/assets/130583246/9677ab8d-2d20-44c1-8157-5581d7c574ee)
