### ISSUE TITLE
Фон карты

### ISSUE THREAD

**Issue by Blobson** [Blobson/break-a-leg#9]

**Comment by Vegostar** [comment]
Изначальный размер фона 680х1740. Скинула еще увеличенный в 6 раз (4080х10440 -- подходит если берем размер экрана 1080х1920 и хотим пять видимых рядов) и 6800х17400 -- максимальный размер (х10) если экспортировать из приложения.

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/7b80f519-d587-4aae-be0e-15c125e5ed89)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/8aad2d35-0638-419f-a1bd-ec797cc07ce8)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/1a48424d-f280-464e-b935-0cc32ad21d3a)

**Comment by Vegostar** [comment]
Размер дома 480х1440 (если 15х45 тайлов по 32 px), добавила 200 px слева+справа, 300 px сверху+снизу для начала и окончания уровня

Пустые фоны с теми же размерами:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/b945246a-78b8-4e3d-9933-fd6c975a491f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/0adf36eb-ff08-4607-88a8-2d974f4c4717)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/cfa0cee4-035e-4919-9f6b-0b52f28189b0)

**Comment by Vegostar** [comment]
Левый край (размеры х1, х10)

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/baa75e2b-2fc6-42b8-a634-9d9cd97ee640)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fc2273f3-ff57-4a70-8001-671668464ed4)

**Comment by Vegostar** [comment]
Правый край

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/d2b2ffd0-4f88-485e-8cad-9ae69ca10b3f)
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/cb2a39d7-5c2b-4dd4-9a88-6b1a5b2769fa)
