### ISSUE TITLE
Подбор шрифта для UI

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#94]

**Comment by Vegostar** [comment]
https://fonts-online.ru/fonts/04b24 -- для заголовков

https://fonts-online.ru/fonts/atlantis-international -- для обычного текста


Сделала для удобства схему с экранами с расположением шрифта:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/e2859f43-ec64-441b-889d-48d589f543c1)
