### ISSUE TITLE
Фон меню (главный экран)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#97]
На выбор:
Курьер пьет кофе на скамейке в парке
Курьер у пруда кормит уток
Курьер крутит трюки на ховер-байке

**Comment by Vegostar** [comment]
Пока что не стала делать анимацию кормления уток, надо глянуть как смотреться будет на экране вместе с телефоном внизу и названием. 

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/fc0f2eb5-5bc8-4613-8ac5-df44ceed9d48)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/aedc85fb-09f3-4518-addb-d577bb067888)
