### ISSUE TITLE
Анимированное название игры в верхней части экрана (главный экран)

### ISSUE THREAD

**Issue by Svedmit** [Blobson/break-a-leg#98]

**Comment by Vegostar** [comment]
![Image](https://github.com/Blobson/break-a-leg/assets/128842278/0f917047-caec-4826-a300-9ccd48ec8c88)



![Image](https://github.com/Blobson/break-a-leg/assets/128842278/ae8fe4c6-3333-476f-b4b8-e84d42230c40)


Фон пока не доделала, но расположение планируется такое:

![Image](https://github.com/Blobson/break-a-leg/assets/128842278/09a020b6-886d-47e7-aec8-dcdeba0b9ec3)

**Comment by Svedmit** [comment]
Красивое 🐟
